### ISSUE TITLE
Configuração de CI

### ISSUE THREAD

**Issue by diegorubin** [marcoslimagon/squad3-script-lang#2]
Um CI para projetos opensource bastante utilizado é o Travis. Ele é gratuito para projetos opensource, porém para projetos privados ele é pago.
 
https://docs.travis-ci.com/user/travis-ci-for-private/

Alguém teria alguma outra sugestão de ferramenta? Ou o que nos impediria de tornar esse projeto público?

**Comment by marcoslimagon** [comment]
Repositório agora é público
